# Application Config
spring.application.name=codenest
server.port=8080

# Thymeleaf Config
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# MongoDB Config (Atlas URI from environment variable or default to local)
spring.data.mongodb.uri=mongodb+srv://codenestproject1_db_user:codenest5@cluster0.qktijer.mongodb.net/codenest?appName=Cluster0

# File Upload sizes (optional for cosmetic/avatars)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Settings
codenest.jwt.secret=6a7072672d7365637265742d6b65792d666f722d636f64652d6e6573742d7270672d616476656e747572652d67616d65
codenest.jwt.expiration-ms=86400000

# Server logging level
logging.level.org.springframework.web=INFO
logging.level.com.codenest=DEBUG

# Email SMTP Configuration (Fill these in to send real emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codenestproject1@gmail.com
spring.mail.password=inyp gpyj ysye cnnf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
